export const TICKERS = [
  'AAPL', 'NVDA', 'MSFT', 'GOOGL', 'AMZN',
  'META', 'TSLA', 'AVGO', 'LLY',  'JPM',
  'V',    'UNH',  'XOM',  'MA',   'COST',
  'JNJ',  'HD',   'NFLX', 'AMD',  'ORCL',
  'WMT',  'PG',   'BAC',  'CRM',  'KO',
  'PEP',  'ABBV', 'MRK',  'TSM',  'INTC',
] as const
export type Ticker = (typeof TICKERS)[number]

export const COMPANIES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  NVDA: 'NVIDIA Corp.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  AMZN: 'Amazon.com Inc.',
  META: 'Meta Platforms Inc.',
  TSLA: 'Tesla Inc.',
  AVGO: 'Broadcom Inc.',
  LLY:  'Eli Lilly and Co.',
  JPM:  'JPMorgan Chase & Co.',
  V:    'Visa Inc.',
  UNH:  'UnitedHealth Group Inc.',
  XOM:  'Exxon Mobil Corp.',
  MA:   'Mastercard Inc.',
  COST: 'Costco Wholesale Corp.',
  JNJ:  'Johnson & Johnson',
  HD:   'Home Depot Inc.',
  NFLX: 'Netflix Inc.',
  AMD:  'Advanced Micro Devices Inc.',
  ORCL: 'Oracle Corp.',
  WMT:  'Walmart Inc.',
  PG:   'Procter & Gamble Co.',
  BAC:  'Bank of America Corp.',
  CRM:  'Salesforce Inc.',
  KO:   'Coca-Cola Co.',
  PEP:  'PepsiCo Inc.',
  ABBV: 'AbbVie Inc.',
  MRK:  'Merck & Co.',
  TSM:  'Taiwan Semiconductor Mfg.',
  INTC: 'Intel Corp.',
}
