// 미국 시가총액 상위 30종목 (2025년 기준)
export const TICKERS = [
  'AAPL', 'NVDA', 'MSFT', 'GOOGL', 'AMZN',
  'META', 'TSLA', 'AVGO', 'WMT',   'LLY',
  'JPM',  'V',    'UNH',  'XOM',   'MA',
  'COST', 'PEP',  'NFLX', 'JNJ',   'PG',
  'ORCL', 'HD',   'BAC',  'AMD',   'CRM',
  'ABT',  'KO',   'MRK',  'ABBV',  'TSM',
] as const
export type Ticker = (typeof TICKERS)[number]

export const COMPANIES: Record<string, string> = {
  AAPL:  'Apple Inc.',
  NVDA:  'NVIDIA Corp.',
  MSFT:  'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  AMZN:  'Amazon.com Inc.',
  META:  'Meta Platforms Inc.',
  TSLA:  'Tesla Inc.',
  AVGO:  'Broadcom Inc.',
  WMT:   'Walmart Inc.',
  LLY:   'Eli Lilly and Co.',
  JPM:   'JPMorgan Chase & Co.',
  V:     'Visa Inc.',
  UNH:   'UnitedHealth Group Inc.',
  XOM:   'Exxon Mobil Corp.',
  MA:    'Mastercard Inc.',
  COST:  'Costco Wholesale Corp.',
  PEP:   'PepsiCo Inc.',
  NFLX:  'Netflix Inc.',
  JNJ:   'Johnson & Johnson',
  PG:    'Procter & Gamble Co.',
  ORCL:  'Oracle Corp.',
  HD:    'Home Depot Inc.',
  BAC:   'Bank of America Corp.',
  AMD:   'Advanced Micro Devices Inc.',
  CRM:   'Salesforce Inc.',
  ABT:   'Abbott Laboratories',
  KO:    'Coca-Cola Co.',
  MRK:   'Merck & Co.',
  ABBV:  'AbbVie Inc.',
  TSM:   'Taiwan Semiconductor Mfg.',
}
