import type { StockAnalysis } from './types'

export const MOCK_STOCKS: StockAnalysis[] = [
  {
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    currentPrice: 213.49,
    changePercent: 1.24,
    rsi: 42.3,
    signal: 'HOLD',
    score: 55,
    reasoning: 'RSI 42.3으로 중립권. iPhone 16 수요 안정적이라는 뉴스 1건. 단기 방향성 불명확.',
    newsItems: [
      { headline: 'Apple iPhone 16 demand remains steady despite macro headwinds', datetime: Date.now() / 1000, url: '#' },
    ],
    lastUpdated: new Date().toISOString(),
    isStale: false,
  },
  {
    ticker: 'NVDA',
    companyName: 'NVIDIA Corp.',
    currentPrice: 875.20,
    changePercent: 3.81,
    rsi: 28.7,
    signal: 'BUY',
    score: 78,
    reasoning: 'RSI 28.7로 강한 과매도. Blackwell GPU 수요 폭증 뉴스 2건. 단기 반등 확률 높음.',
    newsItems: [
      { headline: 'NVIDIA Blackwell GPU demand exceeds supply, analysts raise targets', datetime: Date.now() / 1000, url: '#' },
      { headline: 'Data center AI spending accelerates into Q2 2026', datetime: Date.now() / 1000, url: '#' },
    ],
    lastUpdated: new Date().toISOString(),
    isStale: false,
  },
  {
    ticker: 'TSLA',
    companyName: 'Tesla Inc.',
    currentPrice: 242.15,
    changePercent: -2.34,
    rsi: 72.1,
    signal: 'SELL',
    score: 31,
    reasoning: 'RSI 72.1로 강한 과매수. 유럽 판매 부진 뉴스 2건. 단기 조정 가능성.',
    newsItems: [
      { headline: 'Tesla Europe sales drop 40% YoY amid brand perception issues', datetime: Date.now() / 1000, url: '#' },
      { headline: 'EV price war intensifies, margins under pressure', datetime: Date.now() / 1000, url: '#' },
    ],
    lastUpdated: new Date().toISOString(),
    isStale: false,
  },
  {
    ticker: 'MSFT',
    companyName: 'Microsoft Corp.',
    currentPrice: 421.89,
    changePercent: 0.67,
    rsi: 55.4,
    signal: 'HOLD',
    score: 52,
    reasoning: 'RSI 55.4로 중립권. Azure 클라우드 성장 안정적. 특별한 촉매 없음.',
    newsItems: [
      { headline: 'Microsoft Azure growth stabilizes at 25% YoY', datetime: Date.now() / 1000, url: '#' },
    ],
    lastUpdated: new Date().toISOString(),
    isStale: false,
  },
  {
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    currentPrice: 178.32,
    changePercent: -0.89,
    rsi: 35.8,
    signal: 'BUY',
    score: 65,
    reasoning: 'RSI 35.8로 과매도 진입. AI 검색 광고 수익 개선 뉴스. 중장기 매수 유효.',
    newsItems: [
      { headline: 'Google AI Overviews boosting ad click-through rates by 15%', datetime: Date.now() / 1000, url: '#' },
    ],
    lastUpdated: new Date().toISOString(),
    isStale: false,
  },
]
