import type { StockAnalysis } from './types'

export const MOCK_STOCKS: StockAnalysis[] = [
  {
    ticker: 'AAPL', companyName: 'Apple Inc.',
    currentPrice: 213.49, changePercent: 1.24, rsi: 42.3,
    signal: 'HOLD', score: 55,
    reasoning: 'RSI 42.3으로 중립권. iPhone 수요 안정적. 단기 방향성 불명확.',
    newsItems: [{ headline: 'Apple iPhone demand remains steady amid macro headwinds', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'NVDA', companyName: 'NVIDIA Corp.',
    currentPrice: 875.20, changePercent: 3.81, rsi: 28.7,
    signal: 'BUY', score: 78,
    reasoning: 'RSI 28.7로 강한 과매도. Blackwell GPU 수요 폭증 뉴스 2건. 단기 반등 확률 높음.',
    newsItems: [{ headline: 'NVIDIA Blackwell GPU demand exceeds supply', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'MSFT', companyName: 'Microsoft Corp.',
    currentPrice: 421.89, changePercent: 0.67, rsi: 55.4,
    signal: 'HOLD', score: 52,
    reasoning: 'RSI 55.4로 중립권. Azure 클라우드 성장 안정적. 특별한 촉매 없음.',
    newsItems: [{ headline: 'Microsoft Azure growth stabilizes at 25% YoY', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'GOOGL', companyName: 'Alphabet Inc.',
    currentPrice: 178.32, changePercent: -0.89, rsi: 35.8,
    signal: 'BUY', score: 65,
    reasoning: 'RSI 35.8로 과매도 진입. AI 검색 광고 수익 개선 뉴스. 중장기 매수 유효.',
    newsItems: [{ headline: 'Google AI Overviews boosting ad click-through rates', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'AMZN', companyName: 'Amazon.com Inc.',
    currentPrice: 185.23, changePercent: 1.87, rsi: 48.2,
    signal: 'HOLD', score: 53,
    reasoning: 'RSI 48.2로 중립권. AWS 성장 견조. 광고 사업 호조로 하방 제한.',
    newsItems: [{ headline: 'Amazon AWS revenue beats estimates on AI workload demand', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'META', companyName: 'Meta Platforms Inc.',
    currentPrice: 512.45, changePercent: 2.34, rsi: 62.1,
    signal: 'HOLD', score: 58,
    reasoning: 'RSI 62.1로 중립 상단. 광고 매출 호조. 추가 상승 여력 제한적.',
    newsItems: [{ headline: 'Meta ad revenue surges as AI-powered targeting improves', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'TSLA', companyName: 'Tesla Inc.',
    currentPrice: 242.15, changePercent: -2.34, rsi: 72.1,
    signal: 'SELL', score: 31,
    reasoning: 'RSI 72.1로 강한 과매수. 유럽 판매 부진 뉴스 2건. 단기 조정 가능성.',
    newsItems: [{ headline: 'Tesla Europe sales drop 40% YoY amid brand issues', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'AVGO', companyName: 'Broadcom Inc.',
    currentPrice: 168.32, changePercent: 0.95, rsi: 44.3,
    signal: 'HOLD', score: 51,
    reasoning: 'RSI 44.3으로 중립권. AI 반도체 수요 견조. VMware 통합 순항 중.',
    newsItems: [{ headline: 'Broadcom VMware integration ahead of schedule', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'LLY', companyName: 'Eli Lilly and Co.',
    currentPrice: 792.10, changePercent: -1.23, rsi: 38.5,
    signal: 'BUY', score: 62,
    reasoning: 'RSI 38.5로 과매도 근접. 비만 치료제 Mounjaro 수요 급증. 단기 매수 유효.',
    newsItems: [{ headline: 'Eli Lilly Mounjaro demand continues to outpace supply', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'JPM', companyName: 'JPMorgan Chase & Co.',
    currentPrice: 238.47, changePercent: 0.54, rsi: 52.7,
    signal: 'HOLD', score: 53,
    reasoning: 'RSI 52.7로 중립권. 금리 안정화로 NIM 방어. 투자은행 부문 회복세.',
    newsItems: [{ headline: 'JPMorgan beats Q4 estimates on investment banking rebound', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'V', companyName: 'Visa Inc.',
    currentPrice: 342.15, changePercent: 0.78, rsi: 57.3,
    signal: 'HOLD', score: 55,
    reasoning: 'RSI 57.3으로 중립 상단. 글로벌 결제량 증가. 안정적 성장세 유지.',
    newsItems: [{ headline: 'Visa payment volume grows 8% YoY on travel recovery', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'UNH', companyName: 'UnitedHealth Group Inc.',
    currentPrice: 510.28, changePercent: -0.43, rsi: 41.2,
    signal: 'HOLD', score: 50,
    reasoning: 'RSI 41.2로 중립권. 의료비 증가 압박. 보험료 인상으로 일부 상쇄.',
    newsItems: [{ headline: 'UnitedHealth raises premiums to offset rising medical costs', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'XOM', companyName: 'Exxon Mobil Corp.',
    currentPrice: 112.45, changePercent: 1.12, rsi: 55.8,
    signal: 'HOLD', score: 54,
    reasoning: 'RSI 55.8로 중립권. 유가 안정화. Pioneer 인수 시너지 기대.',
    newsItems: [{ headline: 'ExxonMobil Pioneer acquisition synergies ahead of target', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'MA', companyName: 'Mastercard Inc.',
    currentPrice: 523.67, changePercent: 0.89, rsi: 58.4,
    signal: 'HOLD', score: 56,
    reasoning: 'RSI 58.4로 중립 상단. 크로스보더 결제 성장 지속. 밸류에이션 다소 높음.',
    newsItems: [{ headline: 'Mastercard cross-border volumes up 12% as travel booms', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'COST', companyName: 'Costco Wholesale Corp.',
    currentPrice: 924.35, changePercent: 1.45, rsi: 61.3,
    signal: 'HOLD', score: 59,
    reasoning: 'RSI 61.3으로 중립 상단. 멤버십 갱신율 사상 최고. 밸류에이션 부담.',
    newsItems: [{ headline: 'Costco membership renewal rate hits all-time high of 93%', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'JNJ', companyName: 'Johnson & Johnson',
    currentPrice: 162.78, changePercent: -0.34, rsi: 36.2,
    signal: 'BUY', score: 64,
    reasoning: 'RSI 36.2로 과매도 근접. 탈크 소송 합의 진전. 의약품 파이프라인 견조.',
    newsItems: [{ headline: 'J&J reaches talc settlement progress, overhang clearing', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'HD', companyName: 'Home Depot Inc.',
    currentPrice: 389.21, changePercent: 0.67, rsi: 49.8,
    signal: 'HOLD', score: 52,
    reasoning: 'RSI 49.8로 중립권. 주택 리모델링 수요 회복 중. 금리 하락 수혜 기대.',
    newsItems: [{ headline: 'Home Depot sees remodeling demand pick up as rates fall', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'NFLX', companyName: 'Netflix Inc.',
    currentPrice: 987.43, changePercent: 3.21, rsi: 67.5,
    signal: 'HOLD', score: 57,
    reasoning: 'RSI 67.5로 과매수 근접. 광고 지원 요금제 성장. 추가 상승 여력 제한.',
    newsItems: [{ headline: 'Netflix ad-supported tier surpasses 40M monthly users', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'AMD', companyName: 'Advanced Micro Devices Inc.',
    currentPrice: 112.34, changePercent: -1.87, rsi: 29.3,
    signal: 'BUY', score: 76,
    reasoning: 'RSI 29.3으로 강한 과매도. MI300X GPU 데이터센터 채택 확대. 반등 확률 높음.',
    newsItems: [{ headline: 'AMD MI300X GPU wins major cloud provider contracts', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'ORCL', companyName: 'Oracle Corp.',
    currentPrice: 178.92, changePercent: 1.23, rsi: 53.6,
    signal: 'HOLD', score: 54,
    reasoning: 'RSI 53.6으로 중립권. 클라우드 인프라 수주 증가. AI 데이터센터 수혜.',
    newsItems: [{ headline: 'Oracle cloud infrastructure bookings surge on AI demand', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'WMT', companyName: 'Walmart Inc.',
    currentPrice: 92.34, changePercent: 0.45, rsi: 60.2,
    signal: 'HOLD', score: 57,
    reasoning: 'RSI 60.2로 중립 상단. 저가 소비재 수요 견조. e커머스 성장 지속.',
    newsItems: [{ headline: 'Walmart e-commerce growth accelerates to 21% YoY', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'PG', companyName: 'Procter & Gamble Co.',
    currentPrice: 167.89, changePercent: -0.12, rsi: 43.7,
    signal: 'HOLD', score: 51,
    reasoning: 'RSI 43.7로 중립권. 소비재 수요 안정적. 인플레 완화로 마진 회복.',
    newsItems: [{ headline: 'P&G margins recover as commodity costs normalize', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'BAC', companyName: 'Bank of America Corp.',
    currentPrice: 44.23, changePercent: 0.89, rsi: 47.3,
    signal: 'HOLD', score: 52,
    reasoning: 'RSI 47.3으로 중립권. 금리 안정화로 NII 압박 완화. 소비자 금융 견조.',
    newsItems: [{ headline: 'Bank of America net interest income stabilizes', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'CRM', companyName: 'Salesforce Inc.',
    currentPrice: 289.45, changePercent: 1.67, rsi: 55.9,
    signal: 'HOLD', score: 55,
    reasoning: 'RSI 55.9로 중립권. Agentforce AI 채택 증가. 구독 매출 안정 성장.',
    newsItems: [{ headline: 'Salesforce Agentforce adoption accelerates across enterprise', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'KO', companyName: 'Coca-Cola Co.',
    currentPrice: 71.23, changePercent: 0.23, rsi: 45.1,
    signal: 'HOLD', score: 51,
    reasoning: 'RSI 45.1로 중립권. 이머징마켓 성장 견조. 방어주로 하방 안정적.',
    newsItems: [{ headline: 'Coca-Cola emerging market volumes grow despite FX headwinds', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'PEP', companyName: 'PepsiCo Inc.',
    currentPrice: 161.34, changePercent: -0.45, rsi: 38.9,
    signal: 'BUY', score: 61,
    reasoning: 'RSI 38.9로 과매도 근접. 스낵 부문 수요 회복. 배당 성장 매력적.',
    newsItems: [{ headline: 'PepsiCo snack division volumes recover in North America', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'ABBV', companyName: 'AbbVie Inc.',
    currentPrice: 187.92, changePercent: 0.67, rsi: 52.4,
    signal: 'HOLD', score: 53,
    reasoning: 'RSI 52.4로 중립권. Skyrizi/Rinvoq 성장으로 Humira 공백 보완 중.',
    newsItems: [{ headline: 'AbbVie Skyrizi and Rinvoq revenue offset Humira biosimilar impact', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'MRK', companyName: 'Merck & Co.',
    currentPrice: 129.45, changePercent: -0.89, rsi: 33.7,
    signal: 'BUY', score: 67,
    reasoning: 'RSI 33.7로 강한 과매도. Keytruda 특허 리스크 과도 반영. 매수 기회.',
    newsItems: [{ headline: 'Merck Keytruda patent cliff concerns appear overdone, analysts say', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'TSM', companyName: 'Taiwan Semiconductor Mfg.',
    currentPrice: 178.32, changePercent: 2.34, rsi: 41.8,
    signal: 'HOLD', score: 58,
    reasoning: 'RSI 41.8로 중립권. AI칩 수요로 수주 사상 최대. 지정학적 리스크 상존.',
    newsItems: [{ headline: 'TSMC reports record orders driven by AI chip demand', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
  {
    ticker: 'INTC', companyName: 'Intel Corp.',
    currentPrice: 21.45, changePercent: -3.12, rsi: 26.8,
    signal: 'BUY', score: 72,
    reasoning: 'RSI 26.8로 강한 과매도. 파운드리 사업 구조조정 진행 중. 극단적 저평가 구간.',
    newsItems: [{ headline: 'Intel foundry restructuring plan draws interest from potential partners', datetime: Date.now() / 1000, url: '#' }],
    lastUpdated: new Date().toISOString(), isStale: false,
  },
]
